baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ga-hugo-theme"

[taxonomies]
  tag = "tag"
  category = "categories"
  gear = "gear"
  # singular = plural
  # only required when we add new taxonomies

[params]
  "name" = "Reformat"
  "url" = "https://reformat.co"